project:
  type: website
  output-dir: "docs"

website:
  title: "DEMOS"
  google-analytics: "G-5TFXHJT1JX"
  site-url: https://fcpys.github.io/demos/
  repo-url: https://github.com/FCPyS/demos
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    background: "#95391C"
    foreground: "#FFFCE4"
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Sobre el proyecto"
        file: about.qmd 
      - text: "¿Quienes somos?"
        file: quienes.qmd 
      - text: "Podcast"
        file: podcast.qmd
      - text: "Conversatorio"
        file: conv.qmd
    
  
    
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Recursos"
        contents:
          - recursos.qmd
          - biblio.qmd
      - section: "Talleres"
        contents:
          - talleres.qmd
          - t1_cacenso.qmd
          - t2_endiseg2021.qmd
          - t3_endireh2021.qmd
          - t4_enoe223.qmd
          - t5_texto.qmd
          - t5_texto2.qmd
      - section: "Charla"
        contents:
          - paquetes.qmd


          
  page-footer: 
    left: "Sitio web del Proyecto PAPIME PE303423 Recursos didácticos para la enseñanza de la Sociodemografía"
    right: "con apoyo DGAPA-UNAM"

format:
  html:
    theme:  journal
    css: styles.css
    toc: true
    fontcolor: "#95391C"

editor: visual

