project:
  type: website
  output-dir: "docs"

website:
  title: "DEMOS"
  site-url: https://fcpys.github.io/demos/
  repo-url: https://github.com/FCPyS/demos
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    background: "#95391C"
    foreground: "#FFFCE4"
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Sobre el proyecto"
        file: about.qmd 
      - text: "¿Quienes somos?"
        file: quienes.qmd 
      - text: "Cuestionario"
        file: cuestion.qmd 
      - text: "Recursos en línea"
        file: recursos.qmd


  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Talleres"
        contents:
          - talleres.qmd
          - t1_cacenso.qmd
          - t2_endiseg2021.qmd
          - t3_endireh2021.qmd
          - t4_enoe223.qmd

   
  page-footer: 
    left: "Sitio web del Proyecto PAPIME PE303423 Recursos didácticos para la enseñanza de la Sociodemografía"
    right: "con apoyo DGAPA-UNAM"

format:
  html:
    theme:  journal
    css: styles.css
    toc: true
    fontcolor: "#95391C"

editor: visual

