---
title: "Recursos bibliográficos"
---

## Recursos recomendados por la comunidad demográfica.

Como parte del proyecto se entrevistó a miembros de la comunidad demográfica mexicana, los cuales presentaron algunos textos que para ellos forman parte del acervo básico de bibliografía demográfica.

Haz click en éste [enlace](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/UY8ITIAE/items/ITUH5RR) para acceder a la colección.

## Revistas de Alto impacto.

Además, se llevó a cabo una revisión de los temas de investigación más actuales en las revistas demográficas de alto impacto.

A continuación los artículos recopilados por revista:

-   [Comparative Migratio Studies](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/JIZUYJEA)

-   [Demography](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/E6HY355R)

-   [International Migration Review](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/6KFAU572)

-   [Journal of Demographic Economics](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/IRVDIJ6S)

-   [Journal of Ethnic and Migration Studies](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/2Z6K45ZN)

-   [Journal of Migration and Health](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/TA95QPYQ)

-   [Migration Studies](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/KFP5DDLY)

-   [Population and Development Review](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/GQBENI9H)

-   [Population and Environment](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/5SEC6EEH)

-   [Population Research and Policy Review](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/HZPIV6VA)

-   [Population Studies](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/YVCMDH2C)

-   [Population, Space and Place](https://www.zotero.org/groups/5143839/demos_revistas_q1/collections/3XRGMFVT)
