---
title: "Podcast"
---

## Suscríbete

Tenemos 10 capítulos, *estrenamos los miércoles a las 20 horas (CDMX)*

[Spotify](https://tinyurl.com/demos-podcast) [Amazon](https://music.amazon.com.mx/podcasts/e44029c3-5ccf-4e3d-9070-7c4a1cc819ec/demos) [YouTube](https://www.youtube.com/@DEMOSPAPIME) [Facebook](https://www.facebook.com/PE303423)

## Episodio 1: Introducción al estudio de la población

**Invitado: Jorge Paz**

¿En verdad existe la sobrepoblación? ¿Cuántas personas vivimos en el planeta? ¿Es sostenible que la población crezca a largo plazo? En este episodio el Doctor Jorge Paz nos responderá a todas estas dudas y más. Además de que nos revelará algunos secretos sobre su libro "¡7500 millones de personas!: Qué es y para qué sirve la demografía”

Ligas para comprar el libro: [Siglo XXI](https://sigloxxieditores.com.ar/libro/7500-millones-de-personas/) [Amazon](https://www.amazon.com.mx/%C2%A17500-millones-personas-demograf%C3%ADa-Ciencia-ebook/dp/B0821RQJNM/ref=sr_1_1?adgrpid=1168781542741325&hvadid=73049085138736&hvbmt=be&hvdev=c&hvlocphy=144476&hvnetw=o&hvqmt=e&hvtargid=kwd-73049332114584%3Aloc-119&hydadcr=24048_13576325&keywords=7500+millones+de+personas&qid=1707342093&sr=8-1)

Conductores: Ana Escoto y Oscar Valdés

Locutor: Miguel Cruz

Invitado: Jorge Paz

Editor y Productor: Oscar Valdés

Escúchalo en Spotify

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/19JLyMaYWXXcC9zmGzvPaa?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
[Spotify](https://open.spotify.com/episode/19JLyMaYWXXcC9zmGzvPaa?si=c54c1e51762642c5) [Amazon](https://music.amazon.com.mx/podcasts/e44029c3-5ccf-4e3d-9070-7c4a1cc819ec/episodes/6ec0f2c6-4e23-4537-8ca8-cc5f060e3ff5/demos-cap-1-introducci%C3%B3n-al-estudio-de-la-poblaci%C3%B3n) [YouTube](https://youtu.be/neAixc6ZI5s?si=kEE8nL7BqXyB3xZr) [Facebook](https://fb.watch/qdZYyk9oVN/)

## Episodio 2: Nuevas Fuentes de Información

**Invitada: Victoria Prieto**

¿Qué es una etnoencuesta? ¿Cómo se puede usar a la big data desde la demografía? ¿Cuáles son los alcances y limitaciones de las nuevas fuentes de información digital? En este episodio la Doctora Victoria Prieto nos responderá a todas estas dudas y nos contará la experiencia que tuvo al trabajar con estas nuevas metodologías.

A Victoria la pueden encontrar en **X.com** como: [\@vicprieto10](https://x.com/vicprieto10) y al centro académico de la Universidad de la República del Uruguay como: [\@ppoblacion_uy](https://x.com/PPoblacion_uy)

También, no se olviden de visitar:

-   Sitio del [Observatorio de Movilidad, Infancia y Familia en la Universidad de la República de Uruguay](https://omif.cienciassociales.edu.uy/)

-   Página del Proyecto sobre migración latinoamericana (LAMP). En donde pueden encontrar la etnoencuesta de Inmigración reciente en contextos de acogida latinoamericanos [LAMP-ENIR 2021 Chile / Colombia / Costa Rica](https://mmp-lamp.colmex.mx/)

Conductoras: Ana Escoto y Zyanya Puga

Locutor: Miguel Cruz

Invitada: Victoria Prieto

Editor: Oscar Valdés

Productor: Diego Hernández

Escúchalo en Spotify

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/5f17dBj8REEyo1ib0802px?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
[Spotify](https://open.spotify.com/episode/5f17dBj8REEyo1ib0802px?si=b0fa56f423064786) [Amazon](https://music.amazon.com.mx/podcasts/e44029c3-5ccf-4e3d-9070-7c4a1cc819ec/episodes/f6f6b7d3-0052-433f-9141-2ea2e0bb31eb/demos-cap-2-nuevas-fuentes-de-informaci%C3%B3n) [YouTube](https://youtu.be/KMrrE7omjT0?si=xRbv3a3VAyUQvXTy) [Facebook](https://fb.watch/qd_5umBa8o/)

## Episodio 3: Curso de vida y población

**Invitadas: Edith Pacheco y Nina Castro**

¿Cómo se relaciona Spiderman con la demografía? ¿Cuál es el *turning point* o evento canónico de nuestra generación? ¿Qué es el curso de vida? En este episodio las doctoras Edith Pacheco y Nina Castro nos hablan sobre cómo es aplicar esta metodología en la demografía y cuáles son sus alcances.

Si te interesó el análisis de secuencias checa estas ligas:

-   [Curso Dra. Nina Castro](https://www.youtube.com/watch?v=rBPz2jFy7vE)

-   [Material](https://sites.google.com/politicas.unam.mx/trabajo-pandemia/cursos-y-talleres/curso-taller-an%C3%A1lisis-de-secuencias?authuser=0)

También, aquí está el enlace a las investigaciones de Edith Pacheco junto con Nathaly Llanes:

[Maternidad y trabajo no remunerado en el contexto del Covid-19](http://revistamexicanadesociologia.unam.mx/index.php/rms/article/view/60069)

Conductoras y locutoras: Ana Escoto y Stephanie Alarcón

Invitadas: Edith Pacheco y Nina Castro

Editor y Productor: Oscar Valdés

Escúchalo en Spotify:

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/3PH0O8UQwQ5qPONc63zZ0Y?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
[Spotify](https://open.spotify.com/episode/3PH0O8UQwQ5qPONc63zZ0Y?si=iq7s4ewhRmCB9tphGnjvWw) [Amazon](https://music.amazon.com.mx/podcasts/e44029c3-5ccf-4e3d-9070-7c4a1cc819ec/episodes/d109ea91-2693-4c21-81ee-5d58e3fc83ea/demos-cap-3-curso-de-vida-y-poblaci%C3%B3n) [YouTube](https://youtu.be/xh-0AZMN3vY?si=PG3hN0Ex-vh94USv) y [Facebook](https://fb.watch/qngwk_EE17/)

## Episodio 4: Curso de vida, género y masculinidades

**Invitado: Mario Martínez Salgado**

¿Qué es lo que hace un hombre a un hombre? ¿Dejamos de crecer en la adultez? Todas estas cuestiones las abordaremos en la platica de este día con el doctor Mario Martínez Salgado, quien nos platicará sobre el género y las nuevas masculinidades y su relación con la demografía.

Pueden seguir a Mario en **X.com** como [\@MarioMtzSalgado](https://x.com/@MarioMtzSalgado) y también pueden visitar la página de la Escuela de Métodos que coordina [aquí](http://metodosmorelia.unam.mx/responsables.html)

Conductores: Ana Escoto y Miguel Cruz

Invitado: Mario Martínez Salgado

Locutor, Editor y Productor: Oscar Valdés

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/3dr8tLJnt1H7waeXa8Dfsm?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
[Spotify](https://open.spotify.com/episode/3dr8tLJnt1H7waeXa8Dfsm?si=91fd6c8e434c4bc7) [Amazon](https://music.amazon.com.mx/podcasts/e44029c3-5ccf-4e3d-9070-7c4a1cc819ec/episodes/19f07451-50ad-4f82-9485-df3623992907/demos-cap-4-curso-de-vida-g%C3%A9nero-y-masculinidades) [YouTube](https://www.youtube.com/watch?v=95zjFEw7_pk) [Facebook](https://fb.watch/qwp1FznKGY/)


## Episodio 5: Población y derechos

**Invitado: Mauricio Padrón**


¿Qué son los derechos y por qué es importante tenerlos en cuenta en las investigaciones demográficas? ¿Cómo las investigaciones se relacionan con las políticas públicas? y ¿Cuáles han sido algunas de las grandes controversias entre los datos y los derechos? En este episodio el doctor Mauricio Padrón nos platicará sobre cómo ha sido integrar la dimensión de los derechos a las investigaciones demográficas y en por qué estos son tan importantes a la hora de recopilar y procesar la información.

Te dejamos la liga de la Red Población y Derechos de la Asociación Latinoamericana de Población [aquí](https://www.alapop.org/red-poblacion-y-derechos/)

Locutora: Zyanya Puga 

Conductoras: Ana Escoto y Stephanie Alarcón

Editor y Productor: Oscar Valdés


```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/5BlzIxkk7tfStsWiq2Kq95?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
[Spotify](https://open.spotify.com/episode/5BlzIxkk7tfStsWiq2Kq95?si=3cc40db4040a413e) [Amazon](https://music.amazon.com.mx/podcasts/e44029c3-5ccf-4e3d-9070-7c4a1cc819ec/episodes/8acf4eb1-6640-432d-bb53-8bb6dc88589e/demos-cap-5-poblaci%C3%B3n-y-derechos) [YouTube](https://youtu.be/xSNV7MSKX-Q?si=hjGRjo4idLeoA1bE) [Facebook](https://fb.watch/qFCandPVvS/)

